LiveBlog/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path(
        "hitcount/",
        include(("hitcount.urls", "hitcount"), namespace="hitcount"),
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from blog.views import (
    PostDetailView,
    PostListView,
    UserLoginView,
    UserPasswordResetView,
    UserPasswordChangeView,
    UserPasswordResetConfirmView,
    RegistrationView,
    UserProfileUpdateView,
    PostCreateView,
    UserPostsListView,
    PostDeleteView,
    PostUpdateView,
    SearchView,
    LikePostView,
    LogoutView,
    HomeView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home-page-main"),
    path("home/", HomeView.as_view(), name="home-page"),
    path(
        "accounts/user_posts/", UserPostsListView.as_view(), name="user-posts"
    ),
    path(
        "accounts/post-delete/<int:pk>/",
        PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("post/create/", PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path(
        "post-update/<int:pk>/", PostUpdateView.as_view(), name="post-update"
    ),
    path("posts/", PostListView.as_view(), name="post-list"),
    path("accounts/login/", UserLoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path(
        "accounts/password-change/",
        UserPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("accounts/register/", RegistrationView.as_view(), name="register"),
    path(
        "accounts/password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="blog-templates/accounts/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "accounts/password-reset/",
        UserPasswordResetView.as_view(
            success_url=reverse_lazy("blog:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "accounts/password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="blog-templates/accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password -reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="blog-templates/accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "accounts/user-profile/<int:pk>/",
        UserProfileUpdateView.as_view(),
        name="user-profile",
    ),
    path("search_blogs/", SearchView.as_view(), name="search_blog"),
    path("like/", LikePostView.as_view(), name="like-post"),
]

app_name = "blog"

blog/models.py
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.templatetags.static import static
from django.utils.text import slugify
from django.utils.translation import gettext as _
from autoslug import AutoSlugField
from hitcount.models import HitCount
from taggit.managers import TaggableManager


class User(AbstractUser):
    GENDER_MALE = 1
    GENDER_FEMALE = 2
    GENDER_GENDERLESS = 0
    GENDER_CHOICES = [
        (GENDER_MALE, _("Male")),
        (GENDER_FEMALE, _("Female")),
        (GENDER_GENDERLESS, _("Genderless")),
    ]
    birthday = models.DateField(null=True, blank=True)
    avatar = models.ImageField(
        upload_to="users_photos/",
        default="users_photos/default_user_logged_in.png",
        null=True,
        blank=True,
    )
    gender = models.PositiveSmallIntegerField(
        choices=GENDER_CHOICES, null=True, blank=True
    )
    phone = models.CharField(max_length=32, null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True)

    def save(self, *args, **kwargs):
        if self.username and not self.slug:
            self.slug = slugify(self.username)
        super(User, self).save(*args, **kwargs)

    @property
    def get_avatar(self):
        return (
            self.avatar.url
            if self.avatar
            else static("img/photos_accounts/default_user_logged_in.png")
        )

    @property
    def format_birthday(self):
        if self.birthday:
            return self.birthday.strftime("%d/%B/%Y")
        return ""

    @format_birthday.setter
    def format_birthday(self, value):
        if value:
            self.birthday = datetime.strptime(value, "%d/%B/%Y")
            self.save()


class Post(models.Model):
    title = models.CharField(max_length=256)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="owner_posts"
    )
    content = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)
    liked = models.ManyToManyField(
        User, related_name="liked", default=None, blank=True
    )
    slug = AutoSlugField(populate_from="title")
    picture = models.ImageField(
        upload_to="users_photos_posts",
        default="users_photos_posts/post_default_images.jpeg",
        null=True,
        blank=True,
    )
    tags = TaggableManager()
    hit_count_generic = GenericRelation(
        HitCount,
        object_id_field="object_pk",
        related_query_name="hit_count_generic_relation",
    )

    @property
    def num_likes(self):
        return self.liked.count()


LIKE_CHOICE = (("Dislike", "️🤍"), ("Like", "❤️"))


class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICE, max_length=10, default="♡")

    def __str__(self):
        return str(self.post)


class Comment(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="user_comment"
    )
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="post_comment"
    )
    content = models.TextField()
    created_time_comment = models.DateTimeField(auto_now_add=True)

templates/blog-templates/accounts/password_change.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

  {% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">Change Password</h4>
                <p class="mb-0">Enter your new password here.</p>
              </div>
              <div class="card-body">
                <form method="post" action="#" role="form">
                  {% csrf_token %}

                  {% for field in form %}
                    <div class="mb-3">
                      {{ field }}
                    </div>
                    <span class="text-danger"> {{ field.errors }} </span>
                  {% endfor %}
                  <div class="text-center">
                    <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Change</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div
              class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
            <div
                class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
              <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines"
                   class="position-absolute opacity-4 start-0">
              <div class="position-relative">
                <img class="max-width-500 w-100 position-relative z-index-2"
                     src="{% static 'img/photos_accounts/change-password.png' %}">
              </div>
              <h4 class="mt-1 text-white font-weight-bolder">Change Password </h4>
              <p class="text-white"><b>here you can change the password</b></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

{% block footer %}

  {% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/blog-templates/accounts/password_change_done.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

  {% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">Password Changed</h4>
              </div>
              <div class="card-body">
                Your password has been changed successfully.
              </div>
            </div>
          </div>
          <div
              class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
            <div
                class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
              <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines"
                   class="position-absolute opacity-4 start-0">
              <div class="position-relative">
                <img class="max-width-500 w-100 position-relative z-index-2"
                     src="{% static 'img/photos_accounts/chat.png' %}">
              </div>
              <h4 class="mt-5 text-white font-weight-bolder">"Attention is the new currency"</h4>
              <p class="text-white">The more effortless the writing looks, the more effort the writer actually put into
                the process.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

{% block footer %}

  {% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/blog-templates/accounts/password_reset.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

  {% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">Reset Password</h4>
                <p class="mb-0">Enter your registered email address</p>
              </div>
              <div class="card-body">
                <form method="post">
                  {% csrf_token %}
                  {% for field in form %}
                    <div class="mb-3">
                      {{ field }}
                    </div>
                    <span class="text-danger"> {{ field.errors }} </span>
                  {% endfor %}
                  <div class="text-center">
                    <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Reset</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
          <div
              class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
            <div
                class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
              <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines"
                   class="position-absolute opacity-4 start-0">
              <div class="position-relative">
                <img class="max-width-500 w-100 position-relative z-index-2"
                     src="{% static 'img/photos_accounts/reset_password.png' %}" style="border-radius: 2em">
              </div>
              <h4 class="mt-5 text-white font-weight-bolder">"Reset password"</h4>
              <p class="text-white">you can reset your password here.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

{% block footer %}

  {% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/blog-templates/accounts/password_reset_complete.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

  {% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

  <section>
    <div class="page-header min-vh-100">
      <div class="container">
        <div class="row">
          <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder">Password Changed</h4>
              </div>
              <div class="card-body">
                Your password has been changed successfully. Login again.
                <a class="text-primary" href="{% url 'blog:login' %}">Login</a>
              </div>
            </div>
          </div>
          <div
              class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
            <div
                class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
              <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines"
                   class="position-absolute opacity-4 start-0">
              <div class="position-relative">
                <img class="max-width-500 w-100 position-relative z-index-2"
                     src="{% static 'img/photos_accounts/password_reset_done.jpeg' %}" style="border-radius: 2em;">
              </div>
              <h4 class="mt-5 text-white font-weight-bolder"><b>"All right!"</b></h4>
              <p class="text-white"><b>You can login now!</b></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

{% block footer %}

  {% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/blog-templates/accounts/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your Account {{ user.email }},
  click the link below:
    {{ protocol }}://{{ domain }}{% url 'blog:password_reset_confirm' uidb64=uid token=token %}

  
  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.
  
  Sincerely,
  The Open-Chat Team
{% endautoescape %}

templates/blog-templates/accounts/sign-in.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

  {% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}
  {% if not request.user.is_authenticated %}
    <section>
      <div class="page-header min-vh-100">
        <div class="container">
          <div class="row">
            <div class="col-xl-4 col-lg-5 col-md-7 d-flex flex-column mx-lg-0 mx-auto">
              <div class="card card-plain">
                <div class="card-header pb-0 text-left">
                  <h4 class="font-weight-bolder">Sign In</h4>
                  <p class="mb-0">Enter your email and password to sign in</p>
                </div>
                <div class="card-body">
                  <form method="post" action="#" role="form">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                      {% for error in form.non_field_errors %}
                        <span class="text-danger"> {{ error }} </span>
                      {% endfor %}
                    {% endif %}

                    {% for field in form %}
                      <div class="mb-3">
                        {{ field }}
                      </div>
                      <span class="text-danger"> {{ field.errors }} </span>
                    {% endfor %}
                    <div class="form-check form-switch">
                      <input class="form-check-input" type="checkbox" id="rememberMe">
                      <label class="form-check-label" for="rememberMe">Remember me</label>
                    </div>
                    <a href="{% url "blog:password_reset" %}" class="text-primary text-gradient font-weight-bold">Forgot
                      Password?</a>
                    <div class="text-center">
                      <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign in
                      </button>
                    </div>
                  </form>
                </div>
                <div class="card-footer text-center pt-0 px-lg-2 px-1">
                  <p class="mb-4 text-sm mx-auto">
                    Don't have an account?
                  <form method="get" action="{% url 'blog:register' %}" role="form">
                    {% csrf_token %}
                    

                    <button style=" background-color: transparent;border: none;"   type="submit" ><a class="text-primary text-gradient font-weight-bold">Sign up</a></button>
                  </form>
                  </p>
                </div>

              </div>
            </div>
            <div
                class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
              <div
                  class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
                <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines"
                     class="position-absolute opacity-4 start-0">
                <div class="position-relative">
                  <img class="max-width-400 w-100 position-relative z-index-2 mt-1"
                       src="{% static 'img/photos_accounts/sing_in.png' %}">
                </div>
                <h4 class="mt-1 text-white font-weight-bolder mt-5">Login Page </h4>
                <p class="text-white"><b>Here you can sing in</b></p>
                <div class="position-relative">

                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  {% else %}
    <main>
      <section class="vh-100 d-flex align-items-center justify-content-center">
        <div class="container">
          <div class="row">
            <div class="col-12 text-center d-flex align-items-center justify-content-center">
              <div>
                <img class="img-fluid w-75" src="{% static "img/photos_accounts/404.svg" %}" alt="404 not found">
                <h1 class="mt-5"><span class="font-weight-bolder text-primary">Login detected</span></h1>
                <p class="lead my-4">Oops!t seems like you're already logged into your account.
                  Please proceed to the sections .</p>
                <a class="btn btn-primary animate-hover" href="{% url 'blog:home-page' %}"><i
                    class="fas fa-chevron-left mr-3 pl-2 animate-left-3"></i>Go back home</a>
              </div>
            </div>
          </div>
        </div>
      </section>
    </main>



  {% endif %}
{% endblock content %}
{% block javascripts %}{% endblock javascripts %}
{% block footer %}

  {% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/blog-templates/accounts/sign-up.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Soft UI Design System by Creative Tim {% endblock title %}
{% block body %} class="sign-in-illustration" {% endblock body %}

{% block header %}

  {% include 'includes/navigation.html' %}

{% endblock header %}

{% block content %}

  <section>
    <div class="page-header min-vh-100 ">
      <div class="container mt-7 ">
        <div class="row ">
          <div class="col-xl-4 col-lg-3 col-md-5 d-flex flex-column mx-lg-0 mx-auto">
            <div class="card card-plain">
              <div class="card-header pb-0 text-left">
                <h4 class="font-weight-bolder text-center">Sign Up</h4>
                <p class="mb-0 text-center">Enter your valid credentials to register</p>
              </div>
              <div class="card-body">
                <form method="post" action="#" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% for field in form %}
                    {% if field.name == 'photo' %}
                    {% else %}
                      <div class="mb-3">
                        {{ field }}
                      </div>
                      <span class="text-danger">{{ field.errors }}</span>
                    {% endif %}
                  {% endfor %}
                  <div class="mb-3">

                    <div class="input_container text-center">
                      <label for="files" class="btn">Upload Profile Photo</label>
                      <input name="photo" id="files" style="display:none;" type="file">
                    </div>
                  </div>
                  <script>
                      document.querySelector("#files").onchange = function () {
                          const fileName = this.files[0]?.name;
                          const label = document.querySelector("label[for=files]");
                          label.innerText = fileName ?? "Browse Files";
                      };
                  </script>
                  <div class="text-center">
                    <button type="submit" class="btn btn-lg bg-gradient-primary btn-lg w-100 mt-4 mb-0">Sign Up</button>
                  </div>
                </form>
              </div>
              <div class="card-footer text-center pt-0 px-lg-2 px-1">
                <p class="mb-4 text-sm mx-auto">
                  Already have an account?
                  <a href="{% url 'blog:login' %}" class="text-primary text-gradient font-weight-bold">Sign In</a>
                </p>
              </div>
            </div>
          </div>
        </div>
        <div
            class="col-6 d-lg-flex d-none h-100 my-auto pe-0 position-absolute top-0 end-0 text-center justify-content-center flex-column">
          <div
              class="position-relative bg-gradient-primary h-100 m-3 px-7 border-radius-lg d-flex flex-column justify-content-center">
            <img src="{% static 'img/shapes/pattern-lines.svg' %}" alt="pattern-lines"
                 class="position-absolute opacity-3 start-1">
            <div class="position-relative">
              <img class="max-width-500 w-100 position-relative z-index-2"
                   src="{% static 'img/photos_accounts/chat.png' %}" alt="chat">
            </div>
            <h4 class="mt-5 text-white font-weight-bolder">"Here you can create your account!"</h4>
            <p class="text-white">Sooner register and enjoy the blog!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %}

{% block footer %}

  {% include 'includes/footer_signin.html' %}

{% endblock footer %}

templates/blog-templates/accounts/user_posts.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block title %} Material Kit 2 by Creative Tim {% endblock title %}

{% block body %} class="blog-author bg-gray-100" {% endblock body %}


{% block content %}
  {% load hitcount_tags %}
  <section class="py-sm-7 py-7 position-relative">
    {% include 'blog-templates/posts/dropdowns.html' %}
    <div class="container text-center">
      <h1 style=" background-color: white;
  border-radius: 2em;
  padding: 0.5em;">My posts</h1>
    </div>
    {% if post_list %}
      {% for post in post_list %}
        <div class="container">
          <div class="row">
            <div class="col-12 mx-auto">
              <div class="row py-lg-7 py-5">
                <div class="col-lg-3 col-md-5 position-relative my-auto">
                  {% if post.picture %}
                    <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                         src="{{ post.picture.url }}" alt="{{ post.title }}">
                  {% else %}
                    <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                         src="{% static 'img/photo_posts/post_default_images.jpeg' %}" alt="default picture">
                  {% endif %}
                </div>
                <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
                  <div class="d-flex justify-content-between align-items-center mb-2">
                    <h4 class="mb-0">{{ post.title }}</h4>

                    <div class="d-block">

                      <a href="{% url "blog:user-profile" user_id %}" type="button"
                         class="btn btn-sm btn-outline-info text-nowrap mb-0">My Profile</a>
                      <a href="{% url "blog:post-update" pk=post.pk %}" type="button"
                         class="btn btn-sm btn-outline-warning text-nowrap mb-0">Update Post</a>
                      <button type="button" class="btn btn-sm btn-outline-danger text-nowrap mb-0"
                              data-bs-toggle="modal" data-bs-target="#exampleModal-{{ post.pk }}">Delete Post
                      </button>
                    </div>
                  </div>

                  <div class="row mb-4">
                    <div class="col-auto">
                      <span class="h6">{% get_hit_count for post %}</span>
                      <span>👁</span>
                    </div>
                    <div class="col-auto">
                      <span class="h6">{{ post.liked.all.count }}</span>
                      <span>❤️‍🔥</span>
                    </div>
                    <div class="col-auto">
                      <span class="h6">🗓 {{ post.created_time }}</span>
                      <span>📌</span>
                    </div>
                  </div>
                  <p class="text-lg mb-0">
                    {{ post.content | truncatewords:60 }} <br><a
                      href={% url "blog:post-detail" pk=post.pk %} javascript:
                      class="text-info icon-move-right">continue read
                    <i class="fas fa-arrow-right text-sm ms-1"></i>
                  </a>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="exampleModal-{{ post.pk }}" tabindex="-1" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete the post?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                The post {{ post.title }} will be deleted, changes will be irreversible.
              </div>
              <div class="modal-footer justify-content-between">
                <a href="{% url 'blog:home-page' %}" class="btn bg-gradient-success" data-bs-dismiss="modal">Close</a>

                <form action="{% url 'blog:post-delete' pk=post.pk %}" method="post">
                  {% csrf_token %}
                  <button class="btn  bg-gradient-danger" type="submit">Delete Confirm</button>
                </form>
              </div>
            </div>
          </div>
        </div>

      {% endfor %}
      {% include 'includes/pagination.html' %}
      </section>

    {% else %}
      <div class="container" style="margin-top: 10em;margin-bottom: 8em;">

        <div class="container"
             style="background: cadetblue; width: 50%; margin: 2em auto; padding-bottom: 2em; padding-top: 2em; text-align: center;">
          <h3 style="color: white;">Create first Post!</h3>
          <a href="{% url 'blog:post-create' %}?from_user_first_posts=true" class="btn btn-outline-success text-white">Create
            Post</a>
        </div>
      </div>
    {% endif %}

{% endblock content %}