LiveBlog/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
    path(
        "hitcount/",
        include(("hitcount.urls", "hitcount"), namespace="hitcount"),
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from blog.views import (
    PostDetailView,
    PostListView,
    UserLoginView,
    UserPasswordResetView,
    UserPasswordChangeView,
    UserPasswordResetConfirmView,
    RegistrationView,
    UserProfileUpdateView,
    PostCreateView,
    UserPostsListView,
    PostDeleteView,
    PostUpdateView,
    SearchView,
    LikePostView,
    LogoutView,
    HomeView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home-page-main"),
    path("home/", HomeView.as_view(), name="home-page"),
    path(
        "accounts/user_posts/", UserPostsListView.as_view(), name="user-posts"
    ),
    path(
        "accounts/post-delete/<int:pk>/",
        PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("post/create/", PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/", PostDetailView.as_view(), name="post-detail"),
    path(
        "post-update/<int:pk>/", PostUpdateView.as_view(), name="post-update"
    ),
    path("posts/", PostListView.as_view(), name="post-list"),
    path("accounts/login/", UserLoginView.as_view(), name="login"),
    path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path(
        "accounts/password-change/",
        UserPasswordChangeView.as_view(),
        name="password_change",
    ),
    path("accounts/register/", RegistrationView.as_view(), name="register"),
    path(
        "accounts/password-change-done/",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="blog-templates/accounts/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "accounts/password-reset/",
        UserPasswordResetView.as_view(
            success_url=reverse_lazy("blog:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "accounts/password-reset-done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="blog-templates/accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "accounts/password-reset-confirm/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "accounts/password -reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="blog-templates/accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "accounts/user-profile/<int:pk>/",
        UserProfileUpdateView.as_view(),
        name="user-profile",
    ),
    path("search_blogs/", SearchView.as_view(), name="search_blog"),
    path("like/", LikePostView.as_view(), name="like-post"),
]

app_name = "blog"

templates/blog-templates/posts/dropdowns.html
{% load static %}


{% block content %}

  <div class="col-lg-2 ms-lg-auto col-md-6 col-sm-4 d-flex justify-content-center ">
    <div class="dropdown">
      <button class="btn bg-gradient-primary dropdown-toggle" type="button" id="dropdownMenuButton"
              data-bs-toggle="dropdown" aria-expanded="false">
        Dropdown button
      </button>
      <ul class="dropdown-menu px-2 py-3" aria-labelledby="dropdownMenuButton">
        <li><a class="dropdown-item border-radius-md" href="javascript:">Action</a></li>
        <li><a class="dropdown-item border-radius-md" href="javascript:">Another action</a></li>
        <li><a class="dropdown-item border-radius-md" href="javascript:">Something else here</a></li>
      </ul>
    </div>
  </div>

{% endblock content %}


{% block javascript %}

{% endblock javascript %}

templates/blog-templates/posts/post_create.html
{% extends "layouts/base_sections.html" %}
{% load static %}
{% block header %}
  {% include "includes/navigation.html" %}
{% endblock %}

{% block content %}
  <div class="container">
    <main class="content" style="margin-top: 9em">
      {% if form.errors %}
        <div class="alert alert-danger"
             style="margin-top: 6em; margin-bottom:3em; color: white; text-align: center;border-radius:1em ">
          <strong>Error!</strong> Please correct the following errors:<br>
          {% for field, errors in form.errors.items %}
            {% for error in errors %}
              <p>{{ error }}</p>
            {% endfor %}
          {% endfor %}
        </div>
      {% endif %}
      <form action="#" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <div class="col-12 col-xl-4">
            <div class="row">
              <div class="col-12 mb-4">
                <div class="card border-light text-center p-0">
                  <div class="profile-cover rounded-top"
                       data-background="/static/assets/img/profile-cover.jpg"></div>

                  <div class="card-body pb-4">
                    {% if post_create.picture %}
                      <img src="{{ post_create.picture.url }} "
                           class="user-avatar large-avatar mx-auto  mb-4 custom-avatar"
                           alt="Default photo" style="width: 20em; height:13em; border-radius: 0.75rem !important;">
                    {% else %}
                      <img src=" {% static 'img/photo_posts/post_default_images.jpeg' %}"
                           class="user-avatar large-avatar mx-auto  custom-avatar"
                           alt="default-photo" style="width: 15em; height:13em; border-radius: 0.75rem !important;">

                    {% endif %}

                    <h4 class="h3">{{ profile.user.username }}</h4>
                    <h4 class="font-weight-normal">{{ profile.user.get_full_name }}</h4>
                    <h5 class="font-weight-normal">
                      {{ user_profile.email }}
                    </h5>
                    <p class="text-gray mb-4">{{ profile.address|default:'' }}</p>
                  </div>
                  <div class="col-12 ">
                    <h2 class="h5 mb-3 text-center">Select post photo</h2>
                    <div class="d-flex justify-content-center align-items-center">
                      <div class="input_container">
                        <label for="files" class="btn text-center mb-7 ">Browse Files</label>
                        <input name="picture" id="files" style="display:none;" type="file">
                      </div>
                      <script>document.querySelector("#files").onchange = function () {
                          const fileName = this.files[0]?.name;
                          const label = document.querySelector("label[for=files]");
                          label.innerText = fileName ?? "Browse Files";
                      };</script>
                      <div class="d-md-block text-left">
                        <div class="font-weight-normal text-dark mb-1"></div>
                        <div class="text-gray small"></div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>

            </div>
          </div>
          <div class="col-12 col-xl-8">
            <div class="card card-body bg-white border-light shadow-sm mb-4 text-center">
              <h2 class="h5 mb-4 text-center">Post create</h2>
              <div class="row align-items-center">
                <div class="row">
                  <div class="col-md-6 mb-3 w-100">
                    <div>
                      <label for="title">Title</label>
                      <input name="title" class="form-control text-center" id="title" type="text"
                             placeholder="Enter post title"
                             required>
                    </div>
                  </div>


                  <div class="mb-3">
                    <label for="content">Content</label>
                    <textarea name="content" class="form-control text-center" id="content" rows="6"
                              placeholder="Write your post content here" required></textarea>
                  </div>

                </div>
                <div class="mt-3">
                  <button type="submit" class="btn btn-primary">Create Post</button>
                </div>
              </div>
            </div>

          </div>
      </form>
    </main>
  </div>

{% endblock %}

templates/blog-templates/posts/post_detail.html
{% extends 'layouts/base_sections.html' %}
{% load static %}

{% block header %}
  {% include 'includes/navigation.html' %}
{% endblock header %}

{% block content %}
  {% load hitcount_tags %}
  <section class="py-sm-7 py-5 position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row py-lg-7 py-5">
            <div class="col-lg-3 col-md-5 position-relative my-auto">
              {% if post.picture %}
                <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                     src="{{ post_detail.picture.url }}" alt="image">
              {% else %}
                <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                     src="{% static 'img/photo_posts/post_default_images.jpeg' %}" alt="image">
              {% endif %}
            </div>
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2 text-center">
                <h4 class="mb-0 text-center">{{ post_detail.title }}</h4>
                <div class="d-block">
                  <form class="d-flex" action="{% url "blog:like-post" %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="post_id" value="{{ post_detail.id }}">
                    {% if user not in post_detail.liked.all %}
                      <button value="🤍" type="submit"
                              style=" background-color: transparent;border: none;cursor: pointer;">🤍️
                      </button>
                    {% else %}
                      <button value="❤️" type="submit"
                              style=" background-color: transparent;border: none;cursor: pointer;">❤️
                      </button>
                    {% endif %}
                  </form>
                </div>
              </div>
              <div class="row mb-4 d-flex">
                <div class="col-auto d-flex">
                  <span class="h6"> <b>{% get_hit_count for post_detail %}</b></span>
                  <span><h5 class="ml-1">👁️</h5></span>
                </div>
                <div class="col-auto p-0">
                  <form action="{% url "blog:like-post" %}" method="post">
                    <input type="hidden" name="post_id" value="{{ post_detail.id }}">
                  </form>
                </div>
                <div class="col-auto">
                  <span class="h6"><b>{{ post_detail.liked.all.count }}️</b></span>
                  <span>❤️‍🔥</span>
                </div>
                <div class="col-auto">
                  <span class="h6">🗓 {{ post_detail.created_time }}</span>
                  <span>📌</span>
                </div>
              </div>
              <p class="text-lg mb-0">
                {{ post_detail.content | truncatewords:4000 }} <br>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="py-3">
    <div class="container">
      <section class="py-lg-1">
        <div class="container text-center mt-2 ">
          <h3 class=" color-post-detail z-index-1 position-relative text">Share your views</h3>
          <p class=" color-post-detail opacity-8 mb-0">Share your impressions about the article!</p>
        </div>
        {% for comment in page_obj %}
          <div class="container">
            <div class="row">
              <div class="col-12 mx-auto">
                <div class="row py-lg-7 py-5">
                  <div class="col-lg-3 col-md-5 position-relative my-auto">
                    {% if comment.user.avatar %}
                      <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                           src="{{ comment.user.avatar.url }}" alt="image">
                    {% else %}
                      <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                           src="{% static 'img/users_photos_posts/default_user_logged_in.png' %}" alt="image">
                    {% endif %}
                  </div>
                  <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                      <h4 class="mb-0">{{ comment.user.username }}</h4>
                      <div class="d-block">
                        <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">Author profile
                        </button>
                      </div>
                    </div>
                    <div class="row mb-4">
                      <div class="col-auto">
                        <span class="h6">323</span>
                        <span>Posts</span>
                      </div>
                      <div class="col-auto">
                        <span class="h6">3.5k</span>
                        <span>Followers</span>
                      </div>
                      <div class="col-auto">
                        <span class="h6">{{ comment.created_time_comment }}</span>
                        <span>Data posting</span>
                      </div>
                    </div>
                    <p class="text-lg mb-0">
                      {{ comment.content }}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </section>
    </div>

    {% if not post_detail.post_comment.all %}
      <div class="container" style="background: cadetblue; width: 50%;margin-top:2em;padding-bottom: 1em">
        <hr>
        <h3 style="color: white;text-align: center">Write first commentary!</h3>
      </div>
    {% endif %}
    {% if page_obj %}
      {% include 'includes/pagination.html' %}
    {% endif %}
  </section>

  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <h3 class="text-center">Comments</h3>
        <form role="form" action="" id="contact-form" method="post" autocomplete="off">
          {% csrf_token %}
          <div class="card-body">
            <div class="row">
              <div class="form-group mb-4 form-width">
                <label>Your message</label>
                <textarea name="content" class="form-control" id="message" rows="4"></textarea>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-check form-switch mb-4">
                    <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault" checked="">
                    <label class="form-check-label" for="flexSwitchCheckDefault">I agree to the <a
                        href="javascript:;" class="text-dark"><u>Terms and Conditions</u></a>.</label>
                  </div>
                </div>
                <div class="col-md-12">
                  <button type="submit" class="btn bg-gradient-dark w-100">Send Message</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="container mt-6">
    <div class="row align-items-center text-center">
      <h3 class="mb-5">Check out more useful articles</h3>
    </div>
    <div class="row justify-content-center">
      {% for post in posts|slice:":4" %}
        <div class="col-lg-3 col-sm-6">
          <div class="card card-plain card-blog">
            <div class="card-image border-radius-lg position-relative">
              <a href="{% url 'blog:post-detail' pk=post.pk %}">
                <img class="w-100 border-radius-lg move-on-hover shadow" src="{{ post.picture.url }}"
                     alt="{{ post.title }}">
              </a>
            </div>

            <div class="card-body px-0">
              <h5>
                <a href="{% url 'blog:post-detail' pk=post.pk %}"
                   class="text-dark font-weight-bold">{{ post_detail.title }}</a>
              </h5>
              <div class="row mb-4 d-flex">
                <div class="col-auto d-flex text-center">
                  <span class="h6 justify-content-center"> <b>{% get_hit_count for post_detail %}</b></span>
                  <span><h5 class="ml-1">👁️</h5></span>
                </div>
                <div class="col-auto p-0">
                  <form action="{% url "blog:like-post" %}" method="post">
                    <input type="hidden" name="post_id" value="{{ post_detail.id }}">
                  </form>
                </div>
                <div class="col-auto">
                  <span class="h6"><b>{{ post_detail.liked.all.count }}️</b></span>
                  <span>❤️‍🔥</span>
                </div>
                <div class="col-auto">
                  <span class="h6">🗓 </span>
                  <span><b>{{ post_detail.created_time }}📌</b></span>
                </div>
              </div>
              <p>{{ post.content | truncatewords:30 }}</p>
              <a href="{% url 'blog:post-detail' pk=post.pk %}" class="text-info icon-move-right">Read More <i
                  class="fas fa-arrow-right text-sm"></i></a>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/blog-templates/posts/post_list.html
{% extends 'layouts/base_sections.html' %}
{% load static %}
{% block header %}
  {% include "includes/navigation.html" %}
{% endblock %}
{% block title %} Material Kit 2 by Creative Tim {% endblock title %}

{% block body %} class="blog-author bg-gray-100" {% endblock body %}


{% block content %}
  {% load hitcount_tags %}
  {% if messages %}
    <ul class="messages">
      <h1 style="margin-top: 3em; text-align: center;">Search Results</h1>
      {% for message in messages %}
        <div class="container" style="margin-top: 2em;">
          <div class="alert alert-danger text-white font-weight-bold" role="alert">
            <h5 style="color: white;text-align: center"> {{ message }}</h5>
          </div>
        </div>

      {% endfor %}
    </ul>
  {% endif %}

  {% if search_title %}

    <h1 style="margin-top: 3em; text-align: center;">Search Results</h1>
    {% for search_post in search_title %}
      <div class="container">
      <div class="row">
      <div class="col-12 mx-auto">
      <div class="row py-lg-7 py-5">
      <div class="col-lg-3 col-md-5 position-relative my-auto">
        {% if search_post.picture %}
          <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
               src="{{ search_post.picture.url }}" alt="bruce">
        {% else %}
          <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
               src="{% static 'img/photo_posts/post_default_images.jpeg' %}" alt="bruce">
        {% endif %}

      </div>
      <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
        <div class="d-flex justify-content-between align-items-center mb-2">
          <h4 class="mb-0">{{ search_post.title }}</h4>
          <div class="d-block">
            <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">Author profile</button>
          </div>
        </div>
       
      </div>
    {% endfor %}
  {% endif %}
  {% if not search_title and not messages %}
    {% if post_list != None %}
      <section class="py-sm-7 py-7 position-relative">

        <div class="container text-center mb-5 mt-5">
          <h1 style=" background-color: white;
          border-radius: 2em;
          padding: 0.5em;">Dashboard</h1>
          {% include 'blog-templates/posts/dropdowns.html' %}
        </div>

        <div class="container align-items-center" id="postContainer">
          {% for post in post_list %}
            <div class="container">
              <div class="row">
                <div class="col-12 mx-auto">
                  <div class="row py-lg-7 py-5">
                    <div class="col-lg-3 col-md-5 position-relative my-auto">
                      <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                           src="{{ post.picture.url }}" alt="bruce">
                    </div>
                    <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
                      <div class="d-flex justify-content-between align-items-center mb-2">
                        <h4 class="mb-0">{{ post.title }}</h4>
                        <div class="d-block">

                          <form class="d-flex" action="{% url "blog:like-post" %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value="{{ post.id }}">
                            {% if user not in post.liked.all %}

                              <button value="🤍" type="submit"
                                      style=" background-color: transparent;border: none;cursor: pointer;">🤍️
                              </button>
                            {% else %}
                              <button value="❤️" type="submit"
                                      style=" background-color: transparent;border: none;cursor: pointer;">❤️
                              </button>
                            {% endif %}
                          </form>
                        </div>
                      </div>
                      <div class="row mb-4 d-flex">
                        <div class="col-auto d-flex">
                          <span class="h6"> <b>{% get_hit_count for post %}</b></span>
                          <span><h5 class="ml-1">👁️</h5></span>
                        </div>
                        <div class="col-auto p-0">
                          <form action="{% url "blog:like-post" %}" method="post">
                            <input type="hidden" name="post_id" value="{{ post.id }}">
                          </form>
                        </div>
                        <div class="col-auto">
                          <span class="h6"><b>{{ post.liked.all.count }}️</b></span>
                          <span>❤️‍🔥</span>
                        </div>
                        <div class="col-auto">
                          <span class="h6">🗓 {{ post.created_time }}</span>
                          <span>📌</span>
                        </div>
                      </div>
                      <p class="text-lg mb-0">
                        {{ post.content | truncatewords:60 }} <br><a
                          href={% url "blog:post-detail" post.pk %} javascript:
                          class="text-info icon-move-right">continue read
                        <i class="fas fa-arrow-right text-sm ms-1"></i>
                      </a>
                      </p>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          {% endfor %}
          {% include 'includes/pagination.html' %}
      </section>
    {% else %}
      <div class="container mt-10"
           style="background: cadetblue; width: 50%; margin: 2em auto; padding-bottom: 2em; padding-top: 2em; text-align: center;">
        <h3 style="color: white;">Create first Post!</h3>
        <a href="{% url 'blog:post-create' %}" class="btn btn-outline-success text-white">Create Post</a>
      </div>
    {% endif %}
  {% endif %}

{% endblock content %}

templates/blog-templates/posts/posts_list.html
{% extends 'layouts/base_sections.html' %}
{% load static %}
{% block header %}
  {% include "includes/navigation.html" %}
{% endblock %}
{% block title %} Material Kit 2 by Creative Tim {% endblock title %}

{% block body %} class="blog-author bg-gray-100" {% endblock body %}


{{% block content %}
  {% load hitcount_tags %}
  {% if messages %}
    <ul class="messages">
      <h1 style="margin-top: 3em; text-align: center;">Search Results</h1>
      {% for message in messages %}
        <div class="container" style="margin-top: 2em;">
          <div class="alert alert-danger text-white font-weight-bold" role="alert">
            <h5 style="color: white;text-align: center"> {{ message }}</h5>
          </div>
        </div>
      {% endfor %}
    </ul>
  {% endif %}

  {% if search_title %}
    <h1 style="margin-top: 3em; text-align: center;">Search Results</h1>
    {% for search_post in search_title %}
      <div class="container">
        <div class="row">
          <div class="col-12 mx-auto">
            <div class="row py-lg-7 py-5">
              <div class="col-lg-3 col-md-5 position-relative my-auto">
                {% if search_post.picture %}
                  <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                       src="{{ search_post.picture.url }}" alt="image">
                {% else %}
                  <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                       src="{% static 'img/photo_posts/post_default_images.jpeg' %}" alt="image">
                {% endif %}
              </div>
              <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h4 class="mb-0">{{ search_post.title }}</h4>
                  <div class="d-block">
                    <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0">Author profile</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  {% endif %}

  {% if post_list %}
    <section class="py-sm-5 py-7 position-relative">
      <div class="container text-center mb-5 mt-5">
        <h1 style=" background-color: white;
          border-radius: 2em;
          padding: 0.5em;">Dashboard</h1>
        {% include 'blog-templates/posts/dropdowns.html' %}
      </div>

      <div class="container align-items-center" id="postContainer">
        {% for post in post_list %}
          <div class="container">
            <div class="row">
              <div class="col-12 mx-auto">
                <div class="row py-lg-7 py-5">
                  <div class="col-lg-3 col-md-5 position-relative my-auto">
                    <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2"
                         src="{{ post.picture.url }}" alt="image">
                  </div>
                  <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                      <h4 class="mb-0">{{ post.title }}</h4>
                      <div class="d-block">
                        <form class="d-flex" action="{% url "blog:like-post" %}" method="post">
                          {% csrf_token %}
                          <input type="hidden" name="post_id" value="{{ post.id }}">
                          {% if user not in post.liked.all %}
                            <button value="🤍" type="submit"
                                    style=" background-color: transparent;border: none;cursor: pointer;">🤍️
                            </button>
                          {% else %}
                            <button value="❤️" type="submit"
                                    style=" background-color: transparent;border: none;cursor: pointer;">❤️
                            </button>
                          {% endif %}
                        </form>
                      </div>
                    </div>
                    <div class="row mb-4 d-flex">
                      <div class="col-auto d-flex">
                        <span class="h6"> <b>{% get_hit_count for post %}</b></span>
                        <span><h5 class="ml-1">👁️</h5></span>
                      </div>
                      <div class="col-auto p-0">
                        <form action="{% url "blog:like-post" %}" method="post">
                          <input type="hidden" name="post_id" value="{{ post.id }}">
                        </form>
                      </div>
                      <div class="col-auto">
                        <span class="h6"><b>{{ post.liked.all.count }}️</b></span>
                        <span>❤️‍🔥</span>
                      </div>
                      <div class="col-auto">
                        <span class="h6">🗓 {{ post.created_time }}</span>
                        <span>📌</span>
                      </div>
                    </div>
                    <p class="text-lg mb-0">
                      {{ post.content | truncatewords:200 }} <br><a
                        href={% url "blog:post-detail" post.pk %} javascript:
                        class="text-info icon-move-right">continue read
                      <i class="fas fa-arrow-right text-sm ms-1"></i>
                    </a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        {% include 'includes/pagination.html' %}
      </div>
    </section>
  {% else %}
    <div class="container" style="margin-top: 10em;margin-bottom: 5em">
      <h1 style="background-color: white;
          border-radius: 2em;
          padding: 0.5em; text-align: center">Dashboard</h1>
    </div>

    <div class="container" style="margin-top: 7em;margin-bottom: 10em;">

      <div class="container"
           style="background: cadetblue; width: 50%; margin: 2em auto; padding-bottom: 2em; padding-top: 2em; text-align: center;">
        <h3 style="color: white;">Create first Post!</h3>
        <a href="{% url 'blog:post-create' %}" class="btn btn-outline-success text-white">Create Post</a>
      </div>
    </div>
  {% endif %}
{% endblock %}